language: objective-c
xcode_workspace: Example/VOKMockUrlProtocol.xcworkspace
xcode_scheme: VOKMockUrlProtocol
before_install:
  - brew update
  - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
