language: objective-c
osx_image: xcode7
xcode_workspace: Example/VOKMockUrlProtocol.xcworkspace
xcode_scheme: VOKMockUrlProtocol
xcode_sdk: iphonesimulator
before_install:
  - brew update > /dev/null; if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
